///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ModelPokemonNextEvolution {
/*
{
  "num": "002",
  "name": "Ivysaur"
} 
*/

  String? theNum;
  String? name;

  ModelPokemonNextEvolution({
    this.theNum,
    this.name,
  });
  ModelPokemonNextEvolution.fromJson(Map<String, dynamic> json) {
    theNum = json['num']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['num'] = theNum;
    data['name'] = name;
    return data;
  }
}

class ModelPokemon {
/*
{
  "id": 1,
  "num": "001",
  "name": "Bulbasaur",
  "img": "http://www.serebii.net/pokemongo/pokemon/001.png",
  "type": [
    "Grass"
  ],
  "height": "0.71 m",
  "weight": "6.9 kg",
  "candy": "Bulbasaur Candy",
  "candy_count": 25,
  "egg": "2 km",
  "spawn_chance": 0.69,
  "avg_spawns": 69,
  "spawn_time": "20:00",
  "multipliers": [
    1.58
  ],
  "weaknesses": [
    "Fire"
  ],
  "next_evolution": [
    {
      "num": "002",
      "name": "Ivysaur"
    }
  ]
} 
*/

  int? id;
  String? theNum;
  String? name;
  String? img;
  List<String?>? type;
  String? height;
  String? weight;
  String? candy;
  int? candyCount;
  String? egg;
  double? spawnChance;
  int? avgSpawns;
  String? spawnTime;
  List<double?>? multipliers;
  List<String?>? weaknesses;
  List<ModelPokemonNextEvolution?>? nextEvolution;

  ModelPokemon({
    this.id,
    this.theNum,
    this.name,
    this.img,
    this.type,
    this.height,
    this.weight,
    this.candy,
    this.candyCount,
    this.egg,
    this.spawnChance,
    this.avgSpawns,
    this.spawnTime,
    this.multipliers,
    this.weaknesses,
    this.nextEvolution,
  });
  ModelPokemon.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    theNum = json['num']?.toString();
    name = json['name']?.toString();
    img = json['img']?.toString();
    if (json['type'] != null) {
      final v = json['type'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      type = arr0;
    }
    height = json['height']?.toString();
    weight = json['weight']?.toString();
    candy = json['candy']?.toString();
    candyCount = json['candy_count']?.toInt();
    egg = json['egg']?.toString();
    spawnChance = json['spawn_chance']?.toDouble();
    avgSpawns = json['avg_spawns']?.toInt();
    spawnTime = json['spawn_time']?.toString();
    if (json['multipliers'] != null) {
      final v = json['multipliers'];
      final arr0 = <double>[];
      v.forEach((v) {
        arr0.add(v.toDouble());
      });
      multipliers = arr0;
    }
    if (json['weaknesses'] != null) {
      final v = json['weaknesses'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      weaknesses = arr0;
    }
    if (json['next_evolution'] != null) {
      final v = json['next_evolution'];
      final arr0 = <ModelPokemonNextEvolution>[];
      v.forEach((v) {
        arr0.add(ModelPokemonNextEvolution.fromJson(v));
      });
      nextEvolution = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['num'] = theNum;
    data['name'] = name;
    data['img'] = img;
    if (type != null) {
      final v = type;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['type'] = arr0;
    }
    data['height'] = height;
    data['weight'] = weight;
    data['candy'] = candy;
    data['candy_count'] = candyCount;
    data['egg'] = egg;
    data['spawn_chance'] = spawnChance;
    data['avg_spawns'] = avgSpawns;
    data['spawn_time'] = spawnTime;
    if (multipliers != null) {
      final v = multipliers;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['multipliers'] = arr0;
    }
    if (weaknesses != null) {
      final v = weaknesses;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['weaknesses'] = arr0;
    }
    if (nextEvolution != null) {
      final v = nextEvolution;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['next_evolution'] = arr0;
    }
    return data;
  }
}

class Model {
/*
{
  "pokemon": [
    {
      "id": 1,
      "num": "001",
      "name": "Bulbasaur",
      "img": "http://www.serebii.net/pokemongo/pokemon/001.png",
      "type": [
        "Grass"
      ],
      "height": "0.71 m",
      "weight": "6.9 kg",
      "candy": "Bulbasaur Candy",
      "candy_count": 25,
      "egg": "2 km",
      "spawn_chance": 0.69,
      "avg_spawns": 69,
      "spawn_time": "20:00",
      "multipliers": [
        1.58
      ],
      "weaknesses": [
        "Fire"
      ],
      "next_evolution": [
        {
          "num": "002",
          "name": "Ivysaur"
        }
      ]
    }
  ]
} 
*/

  List<ModelPokemon?>? pokemon;

  Model({
    this.pokemon,
  });
  Model.fromJson(Map<String, dynamic> json) {
    if (json['pokemon'] != null) {
      final v = json['pokemon'];
      final arr0 = <ModelPokemon>[];
      v.forEach((v) {
        arr0.add(ModelPokemon.fromJson(v));
      });
      pokemon = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (pokemon != null) {
      final v = pokemon;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['pokemon'] = arr0;
    }
    return data;
  }
}
